### PR TITLE
Extract Graph API error details for permissions

### LINKED ISSUE #2581: return graph error details when failing to fetch OneDrive item permissions
Details about the reason a call to fetch item permissions are not currently returned. This makes debugging difficult

### PR DESCRIPTION
**Pull request by ashmrtn**
## Description

Add extra information about errors to aid in debugging/reporting to the user

## Does this PR need a docs update or release note?

- [ ] :white_check_mark: Yes, it's included
- [ ] :clock1: Yes, but in a later PR
- [x] :no_entry: No 

## Type of change

- [ ] :sunflower: Feature
- [ ] :bug: Bugfix
- [ ] :world_map: Documentation
- [ ] :robot: Test
- [ ] :computer: CI/Deployment
- [x] :broom: Tech Debt/Cleanup

## Issue(s)

* closes #2581

## Test Plan

- [ ] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

File: src/internal/connector/onedrive/item.go [hunk 1]
```diff
@@ -191,7 +191,7 @@ func oneDriveItemMetaInfo(
 
 	perm, err := service.Client().DrivesById(driveID).ItemsById(*itemID).Permissions().Get(ctx, nil)
 	if err != nil {
-		return Metadata{}, err
+		return Metadata{}, support.ConnectorStackErrorTraceWrap(err, "fetching item permissions")
```
Comment (meain) [inline src/internal/connector/onedrive/item.go:194]: We should probably use `clues` here instead.

Comment (ashmrtn) [reply src/internal/connector/onedrive/item.go]: excellent point, thanks for the reminder

**Review by meain — APPROVED** [review]
