### PR TITLE
Skip creating inline reference attachments

### LINKED ISSUE #999: GC: Restore: Messages: OneDrive Attachment causes error on upload
Restoring a message with a shared OneDrive attachment causes this failure

```bash
 Error Trace:    /corso/src/internal/connector/exchange/exchange_service_test.go:407                                                                
                Error:          Received unexpected error:                                                                                                                                         
                                1 error occurred:                                                                                                                                                  
                                        * ****@someDomain.com:  ErrorInvalidProperty The property '' is required when creating the entity.: error status code received from the API
```

### PR DESCRIPTION
**Pull request by vkamra**
## Description

This fixes #999 by skipping restore of reference attachments that are marked inline.

The attachment links (e.g. OneDrive links) are part of the message body and do not need to be
recreated.

## Type of change

- [ ] :sunflower: Feature
- [x] :bug: Bugfix
- [ ] :world_map: Documentation
- [ ] :robot: Test
- [ ] :computer: CI/Deployment
- [ ] :hamster: Trivial/Minor

## Issue(s)

* #999 

## Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

File: src/internal/connector/exchange/attachment.go [hunk 1]
```diff
@@ -44,9 +44,18 @@ func uploadAttachment(
...
 ) error {
 	logger.Ctx(ctx).Debugf("uploading attachment with size %d", *attachment.GetSize())
+	attachmentType := attachmentType(attachment)
+
+	// Reference attachments that are inline() do not need to be recreated. The contents are part of the body.
+	if attachmentType == models.REFERENCE_ATTACHMENTTYPE &&
+		attachment.GetIsInline() != nil && *attachment.GetIsInline() {
+		logger.Ctx(ctx).Debugf("skip uploading inline reference attachment: ", *attachment.GetName())
+		return nil
+	}
```
Comment (dadams39) [inline src/internal/connector/exchange/attachment.go:54]: The only gotcha is if for whatever reason the email returned as text rather than HTML. This has never been an issue; however, that is a time that the above statement would not be true.

**Review by dadams39 — APPROVED** [review]
Need to fix the linting, but good to go.
