### PR TITLE
Fixups for some Exchange CI bugs

### LINKED ISSUE #2781: CI Failure due to bad reflect comparison
Comparisons with `emptyOrEqual` in the `RestoreAndBackup` test set now appear to be failing with `bad reflect value` if one of the values is nil. Switching to using `ptr.Val` to retrieve item values should be sufficient as it creates an empty value if needed

### LINKED ISSUE #2782: Fix comparison of contact categories
Output from Graph API appears to have changed when it comes to contacts. Contacts that have been restored to a folder are now returned with a category set that includes the folder the item was placed in. This is throwing off Corso [automated tests](https://github.com/alcionai/corso/blob/148a13d7bbe298aea453355233fbacfa92a0a580/src/internal/connector/graph_connector_helper_test.go#L354) as we don't account for the folders we create in the categories of contacts

### PR DESCRIPTION
**Pull request by ashmrtn**
* ignore category values for contacts if the category matches the folder the item is in
* use ptr.Val instead of emptyOrEqual function since the latter wasn't properly handling nil values

Viewing by commit may make things easier

---

#### Does this PR need a docs update or release note?

- [ ] :white_check_mark: Yes, it's included
- [ ] :clock1: Yes, but in a later PR
- [x] :no_entry: No

#### Type of change

- [ ] :sunflower: Feature
- [x] :bug: Bugfix
- [ ] :world_map: Documentation
- [x] :robot: Test
- [ ] :computer: CI/Deployment
- [ ] :broom: Tech Debt/Cleanup

#### Issue(s)

* closes #2781
* closes #2782

#### Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

File: src/internal/connector/graph_connector_helper_test.go [hunk 1]
```diff
@@ -343,7 +344,22 @@ func checkContact(
 	// Not present in msgraph-beta-sdk/models
 	// assert.Equal(t, expected.GetBusinessPhones(), got.GetBusinessPhones())
 
-	assert.Equal(t, expected.GetCategories(), got.GetCategories(), "Categories")
+	// TODO(ashmrtn): Remove this when we properly set and handle categories in
```
Comment (vkamra) [inline src/internal/connector/graph_connector_helper_test.go:347]: @ashmrtn - can you file a ticket for this please?

Comment (vkamra) [reply src/internal/connector/graph_connector_helper_test.go:347]: To handle category correctly

**Review by vkamra — APPROVED** [review]

File: src/internal/connector/graph_connector_helper_test.go (hunk 1 above)
Comment (ashmrtn) [reply src/internal/connector/graph_connector_helper_test.go:347]: see:
* #2785
