### PR TITLE
GC: Restore: Libraries Workflow

### LINKED ISSUE #2489: GC: Restore: Sharepoint: Libraries Workflow
Restore pipeline for `SharePoint.Libraries` causes error when called:
```
folder Corso_Restore_13-Feb-2023_18:30:20 not found in drive(someDrives--mJqq6i) parentFolder(<parent>): failed to get folder <parent>/Corso_Restore_13-Feb-2023_18:30:20. details: : maximum retries or unretryable:  invalidRequest Invalid request: error status code received from the API\n\n"}
```

### PR DESCRIPTION
**Pull request by dadams39**
## Description
Due to recent changes with `Incrementals` restore of Library categories stopped working. This PR will allow for files that do not require special folder permissions to be restored. Changes involve the folder naming format that was coming from the CLI

## Does this PR need a docs update or release note?

- [x] :no_entry: No 

## Type of change

- [x] :bug: Bugfix

## Issue(s)

* closes  #2489<issue>

## Test Plan

- [x] :muscle: Manual

### CODE REVIEW

**Review by ryanfkeepers — APPROVED** [review]

File: src/cli/restore/sharepoint.go [hunk 1]
```diff
@@ -170,7 +170,7 @@ func restoreSharePointCmd(cmd *cobra.Command, args []string) error {
 
 	defer utils.CloseRepo(ctx, r)
 
-	dest := control.DefaultRestoreDestination(common.SimpleDateTime)
+	dest := control.DefaultRestoreDestination(common.SimpleDateTimeOneDrive)
```
Comment (vkamra) [inline src/cli/restore/sharepoint.go:173]: @dadams39 - what regression test can we add to validate restore is working?
