### PR TITLE
remove the last use of multierrs

### LINKED ISSUE #1970: Error processing and management
Error production, management, and tracking throughout corso is largely haphazard, having grown organically within each different package.  A singular, curated error management package would normalize much of the differences, and provide maintenance benefits beyond.

Cases that a singular errors management package would be expected to handle:
1. Coordinating error communication and aggregation.
Throughout graph we have a number of "errUpdater" callback funcs that are passed downstream in order to aggregate lower level errors into a parent multi-err.  We lack a single point of production for parent multi-err, allowing error trees to accrue in place of a singular error list.  Similarly, the functions themselves are often declared anonymously and duplicate similar code, increasing bloat throughout the package.

2. Identifying app behavior after errors.
Corso can be run in one of two error handling modes: fail-fast and best-attempt.  We have various locations which flag the intended state, but application of, and attention to, that flag can vary (or be omitted) depending on the package.  An error manager would provide a central owner for behavior identification.

3. Controlling information flow.
Errors, especially between graph support and pkg/errors, have a variety of options to produce greater or fewer details.  These are things like stack traces, body dumps, etc.  Although those functions exist, we have little means of control for end users to decide how much additional details they want, and when.  An error manager would provide a central owner for toggling greater or lesser amounts of debugging details, as well as the means to coordinate how those details are displayed to the end user through logs and other tools.

4. Normalizing errors for human readable CLI format.
Many of our error states result in a log dump with plenty of chaff info which isn't likely useful to a regular CLI user.  We currently rely on these dumps to identify issues, but as we move towards better logging control and reducing competition between logging and dynamic progress bars, it makes more sense to transform the cli output to a more human readable format.  An error manager would provide a central controller for transforming known error states into well curated outputs in for end users.

### PR DESCRIPTION
**Pull request by ryanfkeepers**
removes the last instance of multierrs in favor of the fault.Bus.

---

#### Does this PR need a docs update or release note?

- [x] :no_entry: No

#### Type of change

- [x] :broom: Tech Debt/Cleanup

#### Issue(s)

* closes #1970

#### Test Plan

- [x] :zap: Unit test

### CODE REVIEW

File: src/internal/connector/exchange/container_resolver.go [hunk 1]
```diff
@@ -193,16 +192,33 @@ func (cr *containerResolver) DestinationNameToID(dest string) string {
...
+			lastErr = err
 		}
 	}
 
-	return errs.ErrorOrNil()
+	if lastErr != nil {
+		return lastErr
+	}
+
+	return nil
```
Comment (meain) [inline src/internal/connector/exchange/container_resolver.go:223]: nit
```suggestion
	return lastErr
```

**Review by meain — APPROVED** [review]
