### PR TITLE
GC: Restore:  `event.item` attachment support

### LINKED ISSUE #2353: GC: Item Attachment Not Supported
Restoring an email with an Item Attachment causes failure. ~Single Value Property cannot be added to the attachment.~ Indicates that portions of the attachment were not downloaded and cannot be uploaded with the property `Item`. 

```bash

* uploading attachment for message <messageID> : ErrorInvalidProperty The property 'Item' is required when creating the entity.: error status code received from the API
<originalMessageID>: failed to upload RestoreExchangeObject: exchange-email: 1 error occurred:

* uploading attachment for message <messageID> : ErrorInvalidProperty The property 'Item' is required when creating the entity.: err
```

Steps:
- [x] Enhance Get option for `ItemAttachmentable` objects
- [ ] Create workflow for restoring `ItemAttachment` types

### PR DESCRIPTION
**Pull request by dadams39**
## Description
`Item.Attachments` of OdataType `Event` require special transformations prior to being uploaded. 

## Does this PR need a docs update or release note?

- [x] :white_check_mark: Yes, it's included

## Type of change

- [x] :sunflower: Feature

## Issue(s)

*closes #2353<issue>

## Test Plan

- [x] :zap: Unit test

### CODE REVIEW

**Comment by dadams39** [comment]
Latest change [aa5a2a0](https://github.com/alcionai/corso/pull/2355/commits/aa5a2a0a7349c94bac0b85089a2db6fff01d5822) ensures nested event template correct and that code will escape non-supported `item.Attachments`
``` bash
=== RUN   TestExchangeRestoreSuite
=== RUN   TestExchangeRestoreSuite/TestRestoreExchangeObject
=== RUN   TestExchangeRestoreSuite/TestRestoreExchangeObject/Test_Mail:_Item_Attachment_NestedEvent
Error returned: exiting ToItemAttachment: #microsoft.graph.message not supported
--- PASS: TestExchangeRestoreSuite (1.75s)
    --- PASS: TestExchangeRestoreSuite/TestRestoreExchangeObject (1.75s)
        --- PASS: TestExchangeRestoreSuite/TestRestoreExchangeObject/Test_Mail:_Item_Attachment_NestedEvent (1.74s)
PASS
```

File: src/internal/connector/exchange/attachment.go [hunk 1]
```diff
@@ -55,19 +60,27 @@ func uploadAttachment(
 
 	// item Attachments to be skipped until the completion of Issue #2353
 	if attachmentType == models.ITEM_ATTACHMENTTYPE {
-		name := ""
-		if attachment.GetName() != nil {
-			name = *attachment.GetName()
+		prev := attachment
+		attachment, err = support.ToItemAttachment(attachment)
+
```
Comment (ryanfkeepers) [inline src/internal/connector/exchange/attachment.go:65]: Nit: standard should be to cuddle funcs that produce errors with `if err != nil` conditionals.
```suggestion

		attachment, err = support.ToItemAttachment(attachment)
```

File: src/internal/connector/exchange/attachment.go [hunk 2]
```diff
@@ -55,19 +60,27 @@ func uploadAttachment(
...
+			}
+
+			logger.Ctx(ctx).Infow("item attachment uploads are not supported ",
+				"attachment_name", name,
+				"attachment_type", attachmentType,
+				"internal_item_type", getItemAttachmentItemType(prev),
+				"attachment_id", *prev.GetId(),
+			)
+
+			fmt.Println("Error returned: " + err.Error())
```
Comment (ryanfkeepers) [inline src/internal/connector/exchange/attachment.go:80]: Debugging statement?  Seems like it could be removed.

File: src/internal/connector/exchange/attachment.go [hunk 3]
```diff
@@ -55,19 +60,27 @@ func uploadAttachment(
...
+
+		if err != nil {
+			// TODO: Update to support PII protection
+			name := ""
+			if prev.GetName() != nil {
+				name = *prev.GetName()
+			}
+
+			logger.Ctx(ctx).Infow("item attachment uploads are not supported ",
+				"attachment_name", name,
```
Comment (ryanfkeepers) [inline src/internal/connector/exchange/attachment.go:74]:
```suggestion
			logger.Ctx(ctx).Infow("item attachment uploads are not supported ",
			        "err", err,
				"attachment_name", name,
```

File: src/internal/connector/support/m365Transform.go [hunk 4]
```diff
@@ -1,11 +1,14 @@
 package support
 
 import (
+	"fmt"
 	"strings"
 
 	"github.com/microsoftgraph/msgraph-sdk-go/models"
 )
 
+const itmAttachment = "#microsoft.graph.itemAttachment"
```
Comment (ryanfkeepers) [inline src/internal/connector/support/m365Transform.go:10]: typo?
```suggestion
const itemAttachment = "#microsoft.graph.itemAttachment"
```

**Review by ryanfkeepers — APPROVED** [review]

File: src/internal/connector/support/m365Transform.go (hunk 4 above)
Comment (dadams39) [reply src/internal/connector/support/m365Transform.go]: Resolved with [1e061c0](https://github.com/alcionai/corso/pull/2355/commits/1e061c08379c783d891e7d8ab727ecddb8b84231)

File: src/internal/connector/exchange/attachment.go (hunk 2 above)
Comment (dadams39) [reply src/internal/connector/exchange/attachment.go]: Resolved within [ba6118d](https://github.com/alcionai/corso/pull/2355/commits/ba6118d34c7bf97dda9dea0bd92b9663b1f9820b)

File: src/internal/connector/exchange/attachment.go (hunk 1 above)
Comment (dadams39) [reply src/internal/connector/exchange/attachment.go]: Resolved within [ba6118d](https://github.com/alcionai/corso/pull/2355/commits/ba6118d34c7bf97dda9dea0bd92b9663b1f9820b)

File: src/internal/connector/exchange/attachment.go (hunk 3 above)
Comment (dadams39) [reply src/internal/connector/exchange/attachment.go]: Resolved within [02c72b8](https://github.com/alcionai/corso/pull/2355/commits/02c72b8d054de268b75b6f723b8a5faccc1d7edd)
