### PR TITLE
Fix NPE in SharePoint incremental backup

### LINKED ISSUE #3306: [Bug]: Merging details during incremental backup fails with older SharePoint backup
### What happened?

Using an older SharePoint backup as the base for an incremental backup in SharePoint causes a nil pointer exception

The root cause is a combination of things. First, SharePoint historically used the OneDriveItem `ItemType`. Second, part of the code for merging backup details switches based on the `ItemType` instead of the presence or absence of data in the model. This led to the code thinking it should attempt to update a OneDriveItemInfo struct instead of a SharePointItemInfo struct

### Corso Version?

Corso v0.7.0

### Where are you running Corso?

N/A

### Relevant log output

```shell
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/debug/stack.go:24 +0x64
github.com/alcionai/corso/src/internal/common/crash.Recovery({0x1064cde98, 0x14001708960}, {0x105643cc0, 0x1082187f0}, {0x104747f89, 0x6})
	/go/src/github.com/alcionai/corso/src/internal/common/crash/crash.go:64 +0x2dc
github.com/alcionai/corso/src/internal/operations.(*BackupOperation).Run.func1()
	/go/src/github.com/alcionai/corso/src/internal/operations/backup.go:128 +0x68
panic({0x105643cc0, 0x1082187f0})
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/panic.go:884 +0x204
github.com/alcionai/corso/src/pkg/backup/details.(*OneDriveInfo).UpdateParentPath(0x0, 0x14002da7220?)
	/go/src/github.com/alcionai/corso/src/pkg/backup/details/details.go:953 +0xbc
github.com/alcionai/corso/src/pkg/backup/details.UpdateItem(0x1064b2550?, 0x14006320ea0?)
	/go/src/github.com/alcionai/corso/src/pkg/backup/details/details.go:642 +0xe4
github.com/alcionai/corso/src/internal/operations.mergeDetails({0x1064cde98, 0x14000e2b980}, 0x14006752301?, {0x1064ce020?, 0x140010c0f80}, {0x14001652598, 0x1, 0x1400063a368?}, {0x1064b2550?, 0x14006320ea0?}, ...)
	/go/src/github.com/alcionai/corso/src/internal/operations/backup.go:733 +0x80c
```

### PR DESCRIPTION
**Pull request by ashmrtn**
Original code was switching based on the ItemType, but SharePoint historically used the OneDriveItem ItemType, making the system think it should be updating a OneDriveItemInfo struct instead of a SharePointItemInfo struct.

Also add a regression test for older backup formats.

---

#### Does this PR need a docs update or release note?

- [x] :white_check_mark: Yes, it's included
- [ ] :clock1: Yes, but in a later PR
- [ ] :no_entry: No

#### Type of change

- [ ] :sunflower: Feature
- [x] :bug: Bugfix
- [ ] :world_map: Documentation
- [ ] :robot: Supportability/Tests
- [ ] :computer: CI/Deployment
- [ ] :broom: Tech Debt/Cleanup

#### Issue(s)

* closes #3306

#### Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

File: src/pkg/backup/details/details.go [hunk 1]
```diff
@@ -628,15 +628,20 @@ func UpdateItem(item *ItemInfo, newLocPath *path.Builder) {
...
+		// keeping the old format.
+		if item.SharePoint.ItemType == OneDriveItem {
+			item.SharePoint.ItemType = SharePointLibrary
+		}
+
 		updatePath = item.SharePoint.UpdateParentPath
-	case OneDriveItem:
+	} else if item.OneDrive != nil {
 		updatePath = item.OneDrive.UpdateParentPath
-	default:
```
Comment (ryanfkeepers) [inline src/pkg/backup/details/details.go:638]: Do we need to keep this as an `else { return }`?

**Review by ryanfkeepers — APPROVED** [review]

File: src/pkg/backup/details/details.go (hunk 1 above)
Comment (ashmrtn) [reply src/pkg/backup/details/details.go:638]: yea, we should. good catch, thanks
