### PR TITLE
GC: Bug Fix: Nested Error Fix

### LINKED ISSUE #1743: GC: Backup: Operation Test Failure
Upgrade of MS Graph libraries has caused certain fields and functions to be deprecated. These affect the functions used in  Incremental backup implementation. This failure is associated with the following test: `TestBackupOpIntegrationSuite/TestBackup_Run_exchange/Integration_Exchange.Mail`
```java
/home/runner/work/corso/corso/src/internal/operations/backup_test.go:412
          	Error:      	Received unexpected error:
          	            	1 error occurred:
          	            		* getting nested object handle: error reading directory: entry not found
```

### PR DESCRIPTION
**Pull request by dadams39**
## Description
Additional Data mapping no longer has delta or next links embedded. After the `msgraph-sdk-go v.41+` upgrade, this data was moved to fields within the struct. PR uses new function calls to make Delta queries.  

## Type of change

- [x] :bug: Bugfix

## Issue(s)

* closes #1743<issue>

## Test Plan
- [x] :zap: Unit test

### CODE REVIEW

**Comment by dadams39** [comment]
Looking promising:
```java
--- PASS: TestBackupOpIntegrationSuite (22.87s)
    --- PASS: TestBackupOpIntegrationSuite/TestBackup_Run_exchange (22.87s)
        --- PASS: TestBackupOpIntegrationSuite/TestBackup_Run_exchange/Integration_Exchange.Mail (22.87s)
PASS
ok  	github.com/alcionai/corso/src/internal/operations	23.548s
```

File: src/internal/connector/exchange/service_iterators.go [hunk 1]
```diff
@@ -349,19 +327,17 @@ func FetchContactIDsFromDirectory(
 			ids = append(ids, *item.GetId())
 		}
 
-		addtlData := resp.GetAdditionalData()
-
-		delta := getAdditionalDataString(deltaLinkKey, addtlData)
-		if len(delta) > 0 {
-			deltaToken = delta
+		delta := resp.GetOdataDeltaLink()
+		if delta != nil {
```
Comment (ashmrtn) [inline src/internal/connector/exchange/service_iterators.go:331]: nit: could you also augment the checks like this to ensure it's not an empty string
```suggestion
		if delta != nil && len(*delta) > 0 {
```

File: src/internal/connector/exchange/service_iterators.go [hunk 2]
```diff
@@ -349,19 +327,17 @@ func FetchContactIDsFromDirectory(
...
+			deltaToken = *delta
 		}
 
-		nextLink := getAdditionalDataString(nextLinkKey, addtlData)
-		if len(nextLink) == 0 {
+		nextLink := resp.GetOdataNextLink()
+		if nextLink == nil {
```
Comment (ashmrtn) [inline src/internal/connector/exchange/service_iterators.go:336]:
```suggestion
		if nextLink == nil || len(*nextLink) == 0 {
```

**Review by ashmrtn — APPROVED** [review]

File: src/internal/connector/exchange/service_iterators.go (hunk 2 above)
Comment (dadams39) [reply src/internal/connector/exchange/service_iterators.go]: Resolved with [f52cf5b](https://github.com/alcionai/corso/pull/1745/commits/f52cf5baae7b45ff44a6aafdca24fb6d8f9b5de4)

File: src/internal/connector/exchange/service_iterators.go (hunk 1 above)
Comment (dadams39) [reply src/internal/connector/exchange/service_iterators.go]: Resolved with [f52cf5b](https://github.com/alcionai/corso/pull/1745/commits/f52cf5baae7b45ff44a6aafdca24fb6d8f9b5de4)
