### PR TITLE
Only remove previous deltas from metadata under some conditions

### LINKED ISSUE #2334: Refactor invalid metadata handling during incremental backups
There may be certain edge cases where we discard metadata from a previous backup in GraphConnector (i.e. incorrectly formatted data etc). In those cases, we don't mark collections as DoNotMerge which could theoretically lead to zombie items in kopia as the base directory will still be merged into the results of the collection.

Overall, we may need a more explicit and direct way to denote what kopia should and shouldn't merge. Whether something should be merged or not may also depend on the service (e.x. Exchange has a delta token per folder but OneDrive has a single delta token for all items)

### PR DESCRIPTION
**Pull request by ashmrtn**
Only allow removing previous delta tokens and not
previous paths. This ensures folder deletions will
be picked up if all items are enumerated

Updates tests to match new behavior, mostly
adjusting expectations around del list when
doNotMerge is applied

---

#### Does this PR need a docs update or release note?

- [ ] :white_check_mark: Yes, it's included
- [ ] :clock1: Yes, but in a later PR
- [x] :no_entry: No

#### Type of change

- [x] :sunflower: Feature
- [ ] :bug: Bugfix
- [ ] :world_map: Documentation
- [ ] :robot: Supportability/Tests
- [ ] :computer: CI/Deployment
- [ ] :broom: Tech Debt/Cleanup

#### Issue(s)

* closes #2334

#### Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

File: src/internal/connector/onedrive/collections.go [hunk 1]
```diff
@@ -199,36 +198,35 @@ func deserializeMetadata(
 				// layers would have caught this. Worst case if we don't handle this
 				// we end up in a situation where we're sourcing items from the wrong
 				// base in kopia wrapper.
-				if errors.Is(err, errExistingMapping) {
-					return nil, nil, clues.Wrap(err, "deserializing metadata file").WithClues(ictx)
+				if err != nil {
```
Comment (meain) [inline src/internal/connector/onedrive/collections.go:201]: We should either keep the old behaviour of failing only for `errExistingMapping` or update the comment to reflect this change.

**Review by meain — APPROVED** [review]
Thanks. I guess it makes sense to keep it similar to Exchange. :D

Need a small change, but approving to unblock.
