### PR TITLE
GC: Backup: SharePoint: Pages Connect Pipeline

### LINKED ISSUE #2071: GC: SharePoint: Backup Site Pages as separate object
- Utilize Microsoft Graph Beta to backup `SharePoint.Pages` as its own object.

### LINKED ISSUE #2257: GC:: Backup: SharePoint:  Pages Status Incorrect
- Upon backup completion of `SharePoint.Pages` the status is not updated (0 Errors and No data). The provided Backup Id shows actual content.

### PR DESCRIPTION
**Pull request by dadams39**
## Description
Finalize the backup workflow for `SharePoint.Pages.`
Populate functions parallelizes
Fix for Incorrect Status during backup

## Does this PR need a docs update or release note?
- [x] :no_entry: No 

## Type of change

- [x] :sunflower: Feature

## Issue(s)

* closes  #2071<issue>
* closes #2257
* related to #2173

## Test Plan
- [x] :zap: Unit test

### CODE REVIEW

**Comment by dadams39** [comment]
- TODO: Verify full workflow with #2213 is merged to ensure all logic in binary to close out #2071.

**Comment by dadams39** [comment]
> * TODO: Verify full workflow with [CLI: Backup: SharePoint:  Pages Enable  #2213](https://github.com/alcionai/corso/pull/2213) is merged to ensure all logic in binary to close out [GC: SharePoint: Backup Site Pages as separate object #2071](https://github.com/alcionai/corso/issues/2071).

- Pipeline verified in https://github.com/alcionai/corso/pull/2221
Bug Fix required -> https://github.com/alcionai/corso/pull/2222

File: src/internal/connector/sharepoint/collection_test.go [hunk 1]
```diff
@@ -167,24 +167,6 @@ func (suite *SharePointCollectionSuite) TestCollection_Items() {
 	}
 }
 
-func (suite *SharePointCollectionSuite) TestCollectPages() {
```
Comment (ashmrtn) [inline src/internal/connector/sharepoint/collection_test.go:170]: do we have other code that exercises the `collectPages` path (directly or indirectly)? Like an integration test or something?

File: src/internal/connector/sharepoint/data_collections.go [hunk 2]
```diff
@@ -180,9 +192,10 @@ func collectPages(
 	spcs := make([]data.BackupCollection, 0)
 
 	// make the betaClient
+	// Need to receive From DataCollection Call
 	adpt, err := graph.CreateAdapter(creds.AzureTenantID, creds.AzureClientID, creds.AzureClientSecret)
 	if err != nil {
-		return nil, errors.Wrap(err, "adapter for betaservice not created")
+		return nil, fmt.Errorf("unable to create adapter w/ env credentials")
```
Comment (ashmrtn) [inline src/internal/connector/sharepoint/data_collections.go:198]: nit: since we're not passing any format args this can be just `errors.New` from either `pkg/errors` or stdlib `errors`. Probably a preference for `pkg/errors` though as it gives stack trace information
```suggestion
		return nil, errors.New("unable to create adapter w/ env credentials")
```

File: src/internal/connector/sharepoint/list.go [hunk 3]
```diff
@@ -91,33 +92,52 @@ func loadSiteLists(
...
+
+			cols, cTypes, lItems, err := fetchListContents(ctx, gs, siteID, id)
+			if err == nil {
+				entry.SetColumns(cols)
+				entry.SetContentTypes(cTypes)
+				entry.SetItems(lItems)
+				updateLists(entry)
+			} else {
+				errUpdater(id, errors.Wrap(err, "unable to fetchRelationships during loadSiteLists"))
+			}
```
Comment (ashmrtn) [inline src/internal/connector/sharepoint/list.go:136]: nit: should handle error case and return, leaving the non-error case unindented
```suggestion
			if err != nil {
				errUpdater(id, errors.Wrap(err, "unable to fetchRelationships during loadSiteLists"))
				return
			}
			
			entry.SetColumns(cols)
			entry.SetContentTypes(cTypes)
			entry.SetItems(lItems)
			updateLists(entry)
```

File: src/internal/connector/sharepoint/list.go [hunk 4]
```diff
@@ -91,33 +92,52 @@ func loadSiteLists(
...
-			continue
-		}
+		go func(id string) {
+			defer wg.Done()
+			defer func() { <-semaphoreCh }()
 
-		results = append(results, entry)
+			entry, err := gs.Client().SitesById(siteID).ListsById(id).Get(ctx, nil)
+			if err != nil {
+				errUpdater(id, support.ConnectorStackErrorTraceWrap(err, ""))
```
Comment (ashmrtn) [inline src/internal/connector/sharepoint/list.go:125]: we need to return here as the below section attempts to set fields on `entry`
```suggestion
				errUpdater(id, support.ConnectorStackErrorTraceWrap(err, ""))
				return
```

File: src/internal/connector/sharepoint/list.go [hunk 5]
```diff
@@ -91,33 +92,52 @@ func loadSiteLists(
...
-		} else {
-			errs = support.WrapAndAppend("unable to fetchRelationships during loadSiteLists", err, errs)
-			continue
-		}
+		go func(id string) {
+			defer wg.Done()
+			defer func() { <-semaphoreCh }()
 
-		results = append(results, entry)
+			entry, err := gs.Client().SitesById(siteID).ListsById(id).Get(ctx, nil)
```
Comment (ashmrtn) [inline src/internal/connector/sharepoint/list.go:123]: does this also need a retry handler?

**Review by ashmrtn — APPROVED** [review]
mostly just nits and some open questions about retries

File: src/internal/connector/sharepoint/api/pages.go [hunk 6]
```diff
@@ -25,16 +26,50 @@ func GetSitePages(
...
+	for _, entry := range pages {
+		semaphoreCh <- struct{}{}
+
+		wg.Add(1)
+
+		go func(pageID string) {
+			defer wg.Done()
+			defer func() { <-semaphoreCh }()
+
+			page, err := serv.Client().SitesById(siteID).PagesById(pageID).Get(ctx, opts)
```
[the remark this answers is not in the document]
Comment (dadams39) [reply src/internal/connector/sharepoint/api/pages.go]: Resolved with [8f8bea9](https://github.com/alcionai/corso/pull/2220/commits/8f8bea9015a993e85aae014aee71da9ad2ced3f5)

File: src/internal/connector/sharepoint/collection_test.go (hunk 1 above)
Comment (dadams39) [reply src/internal/connector/sharepoint/collection_test.go:170]: Oh, yes. This was a duplicate. `TestCollectPages` is in `/sharepoint/data_collections_test.go`.

File: src/internal/connector/sharepoint/list.go (hunk 4 above)
Comment (dadams39) [reply src/internal/connector/sharepoint/list.go:127]: Resolved with [36704e3](https://github.com/alcionai/corso/pull/2220/commits/36704e3ed6baeb42bc09520c807e5f9fb26157a3)

File: src/internal/connector/sharepoint/list.go (hunk 3 above)
Comment (dadams39) [reply src/internal/connector/sharepoint/list.go]: Resolved with [36704e3](https://github.com/alcionai/corso/pull/2220/commits/36704e3ed6baeb42bc09520c807e5f9fb26157a3)

File: src/internal/connector/sharepoint/list.go (hunk 5 above)
Comment (dadams39) [reply src/internal/connector/sharepoint/list.go]: Resolved with [53bdc56](https://github.com/alcionai/corso/pull/2220/commits/53bdc56697017f11ca7b96aa69fced75061790c6)
